[package]
name = "vello_api"
version.workspace = true
description = "Defines the public API types for Vello, providing a stable interface for CPU and Hybrid rendering implementations."
categories = ["rendering", "graphics"]
keywords = ["2d", "vector-graphics"]
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true


[dependencies]

[lints]
workspace = true
