[package]
name = "vello_hybrid"
version.workspace = true
description = "A hybrid CPU/GPU renderer for Vello, balancing computation between CPU and GPU for efficiency."
categories = ["rendering", "graphics"]
keywords = ["2d", "vector-graphics"]
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
# Prevent accidental publishing until the initial release
publish = false

[features]
# Feature for development-only performance measurement
perf_measurement = []

[lints]
workspace = true

[dependencies]
vello_common = { workspace = true }
peniko = { workspace = true }
kurbo = { workspace = true }
bytemuck = { workspace = true, features = ["derive"] }
wgpu = { workspace = true }
winit = "0.30.9"

[dev-dependencies]
pollster = { workspace = true }
png = "0.17.14"
roxmltree = "0.20.0"
